### ISSUE TITLE
Inferkit prompt not defined, InferKit API Error: 500

### ISSUE THREAD

**Issue by DustOfWinter** [KoboldAI/KoboldAI-Client#23]
The inferkit integration seems to be broken. I get an error on line 877 of aiserver.py (prompt is referenced before assignment.)
I tried moving the assignment from 858 to 841, and that sort of fixed it.

But now I'm getting "InferKit API Error: 500 - INVALID_INPUT"

**Comment by KoboldAI** [comment]
Hi, thanks for the report. I just pushed a bugfix to the Git that should resolve this, to should only need to update aiserver.py. Give it a shot and let me know if it works for you.

**Comment by DustOfWinter** [comment]
That fixed the prompt is undefined error, but the InferKit API Error: 500 is still happening. I think it has to do with have a large amount of world entries, or maybe world entries that are too long? I'm not seeing the error at all in a story using the exact same prompt/memory/author's note, but without world info.

**Comment by DustOfWinter** [comment]
After messing around a little bit, I found that inferkit doesn't like submissions longer than 3000 characters. I made some tweaks to how the text is built and I think a better solution is to add the world info last, adding as many entries that fit in the remaining characters before the 3000 cap.

**Comment by KoboldAI** [comment]
Ah, I'm guessing I don't have a cap on the number of tokens/characters WI is allowed to inject, that would make sense. I'll look into adding it.
